name: On PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-lang:
    name: Build Ballerina Lang
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Echo
          env:
            SUPER_SECRET: ${{ secrets.SuperSecret }}
          run: |
            echo ${{ secrets.SuperSecret }}
